export const ADMIN_ROUTES = [
  { path: '/api/admin/ab-tests', label: 'A/B Tests' },
  { path: '/api/admin/admin-users', label: 'Admin Users' },
  { path: '/api/admin/analytics/dashboard', label: 'Analytics Dashboard' },
  { path: '/api/admin/analytics/funnel', label: 'Analytics Funnel' },
  { path: '/api/admin/check-status', label: 'Auth Status Check' },
  { path: '/api/admin/customers', label: 'Customers List' },
  { path: '/api/admin/customers/search', label: 'Customer Search' },
  { path: '/api/admin/dashboard', label: 'Main Admin Dashboard' },
  { path: '/api/admin/notifications', label: 'Notifications' },
  { path: '/api/admin/orders', label: 'Orders List' },
  { path: '/api/admin/products', label: 'Products List' },
  { path: '/api/admin/products/search', label: 'Product Search' },
  { path: '/api/admin/products/stats', label: 'Product Stats' },
  { path: '/api/admin/reviews', label: 'Reviews' },
  { path: '/api/admin/support/categories', label: 'Support Categories' },
  { path: '/api/admin/support/templates', label: 'Support Templates' },
  { path: '/api/admin/support/tickets', label: 'Support Tickets' },
  { path: '/api/admin/system/config', label: 'System Config' },
  { path: '/api/admin/system/email-templates', label: 'Email Templates' },
  { path: '/api/admin/system/health', label: 'System Health' },
  { path: '/api/admin/system/seo/config', label: 'SEO Config' },
  { path: '/api/admin/system/shipping/carriers', label: 'Shipping Carriers' },
  { path: '/api/admin/system/shipping/rates', label: 'Shipping Rates' },
  { path: '/api/admin/system/shipping/zones', label: 'Shipping Zones' },
  { path: '/api/admin/users', label: 'Users Base List' }
];
