export const ADMIN_STATS_REFRESH_INTERVAL = 60000;
export const ADMIN_CHECK_TIMEOUT = 5000;
export const PRODUCTS_STATS_LIMIT = 10000;
export const LOW_STOCK_THRESHOLD = 5;
export const NOTIFICATION_POLL_INTERVAL = 30000;
